experiment:
  name: MGL_DINOv2_v4-baseline-less-class
  seed: 42
training:
  num_classes: ${model.num_classes}
  lr: 0.001
  lr_scheduler: 
    name: "CosineAnnealingLR"
    args:
      T_max: $total_epochs
      eta_min: 0.0000001
  checkpoint: null
  finetune: false
  eval: false
  save_dir: eval_results
  trainer:
    # val_check_interval: 250
    # log_every_n_steps: 100
    # limit_val_batches: 0
    # max_steps: 500000
    # num_epochs: 15
    precision: bf16-mixed
    accelerator: gpu
    strategy: ddp_find_unused_parameters_true
  checkpointing:
    dirpath: checkpoints/
    monitor: val/total/loss
    save_top_k: -1
    mode: min
    save_last: True